### ISSUE TITLE
How to show grid lines and Y-axis values in this chart

### ISSUE THREAD

**Issue by mubashar26** [nhatminh12369/BarChart#2]
i want to show vlaues on y-axis and also grid lines in barchart background.How it can be done?

**Comment by nhatminh12369** [comment]
Hi @mubashar26,

You can look at drawHorizontalLines() method to have an idea on how to draw grid lines. Basically, each line is an instance of CAShapeLayer and the path of CAShapeLayer can be defined using UIBezierPath.

To show value on y-axis, you can use UILabel or CATextLayer to create a label and then add it to the background view or background layer. However, you need to calculate the frame of the label by yourself.

I hope this answers your question :)
