### ISSUE TITLE
Tap on BarChart 

### ISSUE THREAD

**Issue by Jignesh-Gangajaliya** [nhatminh12369/BarChart#4]
Hi,
How to tap into the particular bar? I am using BasicBarChart.

Thanks in advance.

**Comment by Jignesh-Gangajaliya** [comment]
I need to perform action base on Bar Touch.

**Comment by nhatminh12369** [comment]
Hi @JackyGajjar ,

The sample source code doesn't bundle with touch interaction handler. So, you will need to handle it yourself.

There are several ways to implement it. One simple way is to override touchesBegan, touchesEnded.. in BasicBarChart. Based on the location of the touch event, you can calculate which bar has user tapped on.

I hope this will help.

**Comment by Jignesh-Gangajaliya** [comment]
Hi @nhatminh12369, yes we can do this thing for touch interaction and I will try it,
Thanks For Replying.
