### ISSUE TITLE
The title is not wrapping up and displaying in multi line. Could some one let me know how to do it.

### ISSUE THREAD

**Issue by DeepikaUdayakumar** [nhatminh12369/BarChart#5]
Title of 2 bars getting overlapped. need help!
![screen shot 2018-04-05 at 4 21 48 pm](https://user-images.githubusercontent.com/31204405/38362181-84f759d8-38ed-11e8-8725-4dfbe77e0be9.png)

**Comment by nhatminh12369** [comment]
Hi @DeepikaUdayakumar,

You can go to BeautifulBarChart.swift and look for the method named "drawTitle", that's where you need to make some modification. Probably you can change the height of the CATextLayer and set the "isWrapped" property to true.

I hope that helps!

**Comment by DeepikaUdayakumar** [comment]
Thanks for your reply. I tried this yesterday itself. Still it is not working. The text doesn't wrap. 
The library is really great and awesome, but if it has the text wrap working fine, it would be more
great.

![screen shot 2018-04-06 at 12 31 23 pm](https://user-images.githubusercontent.com/31204405/38407310-91456352-3996-11e8-9082-6c0954ef6884.png)

**Comment by nhatminh12369** [comment]
isWrapped property works fine, however it is because I have CATextLayer's frames overlapped. I will commit a fix for it later.

Here is a temporary fix for it:
```
textLayer.frame = CGRect(x: xPos + barWidth/4, y: yPos, width: barWidth/2, height: 60)
textLayer.isWrapped = true
```

**Comment by DeepikaUdayakumar** [comment]
Thanks a lot it worked.

![screen shot 2018-04-06 at 1 29 41 pm](https://user-images.githubusercontent.com/31204405/38409322-a7996f10-399e-11e8-9282-35375531220a.png)
