### ISSUE TITLE
BarChart Frame not change

### ISSUE THREAD

**Issue by ThakarRajesh** [nhatminh12369/BarChart#7]
I have update barFrame but not chart proper display 
Here Is Screenshot please see and Replay fast
![simulator screen shot - iphone 8 plus - 2018-08-25 at 11 33 07](https://user-images.githubusercontent.com/14832892/44615572-a8f5bc80-a85a-11e8-9684-2b576a2f1f93.png)
@nhatminh12369 issue are resolved then let me know

**Comment by nhatminh12369** [comment]
I'm not quite sure what you are asking. But please bear in mind that what I have developed is not a chart library and you shouldn't import it directly into your project. However, you should learn to develop it on your own.

**Comment by ThakarRajesh** [comment]
Ok Thank you

**Comment by nhatminh12369** [comment]
You're welcome
