### ISSUE TITLE
Pod

### ISSUE THREAD

**Issue by mittalkamal29** [nhatminh12369/BarChart#9]
Hi

Can you please add details regrading Pod? 
I mean, How to add library via Pod?

Thanks
Kamal

**Comment by MarcSteven** [comment]
@woodenlabs  u can contribute to the requirement ...

**Comment by nhatminh12369** [comment]
Currently, it is not available via pod. 

You can download the source code directly and import the files manually  into your project.

**Comment by MarcSteven** [comment]
[PNChart](https://github.com/kevinzhow/PNChart) is a great framework to do your job!!!
@woodenlabs

**Comment by MarcSteven** [comment]
@nhatminh12369  BarChart and LineChar are both chart ,so why not do this together???

**Comment by nhatminh12369** [comment]
@MarcSteven 
Well, my intention was not to create a chart library but to guide people how to build the chart themselves. BarChart and LineChart repositories was created along with 2 tutorials on Medium. You can read them here: https://medium.com/@leonardnguyen/build-your-own-chart-in-ios-part-1-bar-chart-e1b7f4789d70

**Comment by MarcSteven** [comment]
Oh,cool
